#portraits
image anna portrait = "images/characters/portraits/anna portrait.png"
image anna dead = "images/characters/portraits/anna dead portrait.png"
image sarah portrait = "images/characters/portraits/sarah portrait.png"
image sarah dead = "images/characters/portraits/sarah dead portrait.png"
image rick portrait = "images/characters/portraits/rick portrait.png"
image rick dead = "images/characters/portraits/rick dead portrait.png"
image lydia portrait = "images/characters/portraits/lydia portrait.png"
image lydia dead = "images/characters/portraits/lydia dead portrait.png"
image orion portrait = "images/characters/portraits/orion portrait.png"
image orion dead = "images/characters/portraits/orion dead portrait.png"
image aster portrait = "images/characters/portraits/aster portrait.png"
image aster dead = "images/characters/portraits/aster dead portrait.png"

image violet portrait = "images/characters/portraits/violet portrait.png"
image violet dead = "images/characters/portraits/violet portrait.png"
image unknown portrait = "images/characters/portraits/unknown portrait.png"
