image bg carlayout = "Backgrounds/bg Barlayout.png"
image bgnotebook = "UserInterface/Notebook.png"
image notebookdead = "images/UserInterface/NotebookDead.png"
image goodIndicator = "images/UserInterface/GoodIndicator.png"
image badIndicator = "images/UserInterface/BadIndicator.png"