image bg carlayout = "Backgrounds/bg Barlayout.png"
image bgnotebook = "UserInterface/Notebook.png"
image notebookdead = "images/UserInterface/NotebookDead.png"
image goodindicator = "images/UserInterface/BadIndicator.png"
image badindicator = "images/UserInterface/GoodIndicator.png"